server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.236.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: false
    ip-address: 127.0.0.1
ly:
  jwt:
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN